spring.application.name=clinica


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuracion necesaria para que RabbitMQ serialice/deserialice JSON de forma nativa
spring.mvc.format.date-time=iso


spring.rabbitmq.listener.type=simple
# Activar los reintentos automaticos del lado del consumidor
spring.rabbitmq.listener.simple.retry.enabled=true
# Numero maximo de intentos (1 intento original + 2 reintentos)
spring.rabbitmq.listener.simple.retry.max-attempts=3
# Intervalo inicial de espera entre reintentos (1 segundo)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
# Multiplicador para aplicar un "backoff" exponencial (ej: 1s, 2s, 4s...)
spring.rabbitmq.listener.simple.retry.multiplier=2.0
# IMPORTANTE: Si es false, al agotar reintentos el mensaje va al DLX configurado.
spring.rabbitmq.listener.simple.retry.stateless=true

spring.rabbitmq.listener.simple.default-requeue-rejected=false


spring.datasource.url=jdbc:oracle:thin:@192.168.56.101:1521/ORCL
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=DEBUG